# Generated by Django 4.2 on 2023-04-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0002_alter_profile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='comment',
            field=models.TextField(max_length=5000),
        ),
    ]
