# Generated by Django 4.2 on 2023-04-12 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0006_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PostApp.profile')),
            ],
        ),
    ]
