# Generated by Django 4.2 on 2023-04-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0008_follower_who_followed_alter_follower_who_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
