# Generated by Django 4.2 on 2023-04-12 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0009_follower_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='status',
            new_name='is_followed',
        ),
    ]
