# Generated by Django 4.2 on 2023-04-12 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0010_rename_status_follower_is_followed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='is_followed',
        ),
    ]
