# Generated by Django 4.2 on 2023-08-07 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0011_remove_follower_is_followed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlike',
            name='is_liked',
        ),
    ]
