# Generated by Django 4.2 on 2023-08-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0012_remove_postlike_is_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Title'),
        ),
    ]
